#!/usr/bin/env python
import subprocess
from time import sleep
x=0
while (x<10):
	try:
 	 result = subprocess.check_output(['evainshmwangiu_upkamaudate', '--profile', 'developer'])
 	 print(result)
	except Exception as e:
 	 print('failure: {}.'.format(e))
	else:
 	 print('success')
++x
